server:
  tomcat:
    uri-encoding: UTF-8
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/ourtalk?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    sql-script-encoding: UTF-8
  jpa:
    hibernate:
      ddl-auto: update #当无数据库创建，有数据库时更新
    database: MYSQL #数据库类型
  #    show-sql: true
  #    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect  #不加这句则默认为myisam引擎
  http:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
  redis:
    host: 127.0.0.1
    port: 6379
  task:
    execution:
      pool:
        core-size: 10
        max-size: 100
        queue-capacity: 1000
        keep-alive: 300s
      thread-name-prefix: defaultAsync-
  servlet:
    multipart:
      enabled: true
      max-file-size: 1024MB
      max-request-size: 1024MB
